version: '3.9'

services:
  # Execute "docker exec -it django-app-dev python manage.py makemigrations" and
  # "docker exec -it django-app-dev python manage.py migrate" from terminal for database migrations.
  smart_map:
    container_name: django-app-dev
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - ./env/local.env
    restart: always

  smart_map_cloud:
    container_name: django-app-prod
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./creds.json:/secrets/creds.json
    env_file:
      - ./env/prod.env
    depends_on:
      - cloudsqlproxy
    links:
      - cloudsqlproxy
    restart: always

  # The proxy will help us connect to remote CloudSQL instance locally.
  # Make sure to turn off any VPNs for the proxy to work.
  cloudsqlproxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    volumes:
      - ./creds.json:/secrets/cloudsql/creds.json
    ports:
      - 127.0.0.1:5432:5432
    command: /cloud_sql_proxy -instances="nsf-2131193-18902:us-central1:smart-map-db-instance"=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/creds.json
    restart: always