# Generated by Django 4.0.5 on 2022-07-13 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('driver', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('access_busdriver_pages', 'Can access bus driver pages.')],
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TransitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_known_lat', models.FloatField()),
                ('last_known_lng', models.FloatField()),
                ('last_bus_stop', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('bus_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busdriver')),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busroute')),
            ],
        ),
        migrations.CreateModel(
            name='BusRouteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_index', models.PositiveSmallIntegerField()),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busstop')),
                ('parent_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busroute')),
            ],
            options={
                'verbose_name_plural': 'Bus Route Details',
            },
        ),
        migrations.AddField(
            model_name='busroute',
            name='first_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_stop',
                                    to='bus.busstop'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='last_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_stop',
                                    to='bus.busstop'),
        ),
    ]
