# Generated by Django 4.0.5 on 2022-06-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BusRouteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_index', models.PositiveSmallIntegerField()),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busstop')),
                ('parent_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busroute')),
            ],
        ),
        migrations.AddField(
            model_name='busroute',
            name='first_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_stop', to='bus.busstop'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='last_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_stop', to='bus.busstop'),
        ),
    ]
