# Generated by Django 4.0.5 on 2022-06-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busroutedetails',
            options={'verbose_name_plural': 'Bus Route Details'},
        ),
    ]
