# Generated by Django 4.0.5 on 2022-06-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_busroutedetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
