# Generated by Django 4.0.5 on 2022-07-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_busroute_color_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'buses'},
        ),
        migrations.AlterModelOptions(
            name='busroutedetails',
            options={'verbose_name_plural': 'bus route details'},
        ),
    ]
