# Generated by Django 4.0.5 on 2022-06-28 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_busdriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_known_lat', models.FloatField()),
                ('last_known_lng', models.FloatField()),
                ('last_bus_stop', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('bus_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busdriver')),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busroute')),
            ],
        ),
    ]
