# Generated by Django 4.0.5 on 2022-07-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_alter_bus_options_alter_busroutedetails_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transitlog',
            old_name='start_time',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='transitlog',
            name='bus_driver',
        ),
        migrations.RemoveField(
            model_name='transitlog',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='transitlog',
            name='last_bus_stop',
        ),
        migrations.RemoveField(
            model_name='transitlog',
            name='last_known_lat',
        ),
        migrations.RemoveField(
            model_name='transitlog',
            name='last_known_lng',
        ),
        migrations.AddField(
            model_name='transitlog',
            name='driver',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transitlog',
            name='bus_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bus.busroute'),
        ),
        migrations.CreateModel(
            name='TransitLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('transit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.transitlog')),
            ],
        ),
    ]
