# Generated by Django 4.0.5 on 2022-07-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_rename_start_time_transitlog_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitlogentry',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
