# Generated by Django 3.2.13 on 2022-07-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_transitlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('route', models.CharField(max_length=200)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.busdriver')),
            ],
        ),
    ]
