# Generated by Django 4.0.5 on 2022-07-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_transitlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('driver', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=200)),
            ],
        ),
    ]
