# Generated by Django 4.0.5 on 2022-07-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_alter_transitlogentry_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='transit_log_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
