# Generated by Django 4.0.5 on 2022-08-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_bus_transit_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='gmaps_polyline_encoding',
            field=models.TextField(default=''),
        ),
    ]
