# Generated by Django 4.0.5 on 2022-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_alter_bus_end_time_alter_bus_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='gmaps_polyline_encoding',
            field=models.TextField(default=''),
        ),
    ]
