# Generated by Django 4.0.5 on 2022-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_busroute_gmaps_polyline_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='color_code',
            field=models.CharField(default='#FF0000', max_length=10),
        ),
    ]
