# Generated by Django 4.0.5 on 2022-08-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_alter_busroute_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='gmaps_polyline_bounds',
            field=models.CharField(default='', max_length=200),
        ),
    ]
