# Generated by Django 4.0.5 on 2022-08-13 21:56

import bus.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_busroute_gmaps_polyline_bounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=1)),
                ('scheduled_time', models.TimeField(default=bus.models.default_time)),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busroute')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busstop')),
            ],
        ),
    ]
