# Generated by Django 4.0.5 on 2022-08-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_busroute_gmaps_polyline_bounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='open_seats_status_color',
            field=models.CharField(default='green', max_length=50),
        ),
    ]
