# Generated by Django 4.0.5 on 2022-08-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0012_bus_open_seats_status_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='open_seats_status_color',
            new_name='seat_availability',
        ),
    ]
