# Generated by Django 4.0.5 on 2022-12-30 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0013_bus_seat_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusArrivalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bus.busroute')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='arrival_log_id',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bus',
            name='latest_route_stop_index',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bus',
            name='position_update_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='BusArrivalLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_driver', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('bus_stop_id', models.PositiveIntegerField(default=None)),
                ('estimated_arrival_time', models.DateTimeField(default=None)),
                ('actual_arrival_time', models.DateTimeField(default=None)),
                ('bus_arrival_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busarrivallog')),
            ],
        ),
    ]
